// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7XKve0FGTcMNvHEywyXsNTrisTgQKsTM',
    appId: '1:894884637300:web:37bacab00963bb87dabf21',
    messagingSenderId: '894884637300',
    projectId: 'coach-dashboard-7b966',
    authDomain: 'coach-dashboard-7b966.firebaseapp.com',
    storageBucket: 'coach-dashboard-7b966.firebasestorage.app',
    measurementId: 'G-5STFCC02HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUnWqlK3DjV7YwLXeVeOQ3BOdg3GxFcs',
    appId: '1:894884637300:android:3a885c38a8f6049adabf21',
    messagingSenderId: '894884637300',
    projectId: 'coach-dashboard-7b966',
    storageBucket: 'coach-dashboard-7b966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOY-SO1XSKVpoqtpgC0ZZbrAkVstqf4Nw',
    appId: '1:894884637300:ios:185cccf4ce6f4b1cdabf21',
    messagingSenderId: '894884637300',
    projectId: 'coach-dashboard-7b966',
    storageBucket: 'coach-dashboard-7b966.firebasestorage.app',
    iosBundleId: 'com.coachclient.app',
  );
}
